// <auto-generated />
namespace myTrack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class myTrackAuth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(myTrackAuth));
        
        string IMigrationMetadata.Id
        {
            get { return "201706070010089_myTrackAuth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
